on:
  workflow_dispatch:
    inputs:
      date_from:
        description: 'Период: с (YYYY-MM-DD)'
        required: false
      date_to:
        description: 'Период: по (YYYY-MM-DD)'
        required: false

jobs:
  run-etl:
    runs-on: ubuntu-latest

    env:
      NEON_HOST: ${{ secrets.NEON_HOST }}
      NEON_DB: ${{ secrets.NEON_DB }}
      NEON_USER: ${{ secrets.NEON_USER }}
      NEON_PASSWORD: ${{ secrets.NEON_PASSWORD }}

      REPORT_ID: ${{ secrets.REPORT_ID }}

      IIKO_BASE_URL: ${{ secrets.IIKO_BASE_URL }}
      IIKO_LOGIN: ${{ secrets.IIKO_LOGIN }}
      IIKO_PASS_SHA1: ${{ secrets.IIKO_PASS_SHA1 }}
      IIKO_VERIFY_SSL: ${{ secrets.IIKO_VERIFY_SSL }}

      TRANSACTION_TYPES: ${{ secrets.TRANSACTION_TYPES }}
      PRODUCT_TYPES: ${{ secrets.PRODUCT_TYPES }}
      RAW_DIR: ${{ secrets.RAW_DIR }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ETL
        run: |
          if [ -n "${{ inputs.date_from }}" ] && [ -n "${{ inputs.date_to }}" ]; then
            DATE_FROM=${{ inputs.date_from }} DATE_TO=${{ inputs.date_to }} python etl.py
          else
            python etl.py
          fi
